# Q1 — Online Food Delivery System
print("======================================================")
print("          Q1 — Online Food Delivery System")
print("======================================================")
foods = ["Burger", "Pizza", "Fries", "Broast", "Sandwich"]
print("First Food Item:", foods[0])
print("Last Food Item:", foods[-1])
foods[2] = "Pasta"
print("Replace 'Fries' with 'Pasta':", foods)
foods.append("Zinger")
print("Add 'Zinger' at the end:", foods)
foods.insert(2, "Shawarma")
print("Insert 'Shawarma' at the index 2:", foods)
foods.remove("Pizza")
print("Remove 'Pizza':", foods)
foods.pop()
print("Remove last item using pop():", foods)
print("Print Total items using 'len()':" ,len(foods))
print("First three items:", foods[0:3])
print("First two items:", foods[-2:])
foods.reverse()
print("Reverse the list:", foods)
foods.sort()
print("Sort the list:", foods)
print("Final Updated List:", foods)

# Q2 — Student Attendance Management
print("======================================================")
print("           Q2 — Student Attendance Management")
print("======================================================")
students = ["Ali", "Sara", "Ahmed", "Zoha Khan", "Hira"]
print("Second Student: ", students[1])
print("Last Student (using negative slicing):", students[-1])
students[2] = "Hamza"
print("Replace 'Ahmed' into 'Hamza':", students)
students.append("Fatima")
print("Add 'Fatima' in the list:", students)
students.insert(1, "Ayesha")
print("Insert 'Ayesha' at index 1:", students)
students.remove("Sara")
print("Remove 'Sara':", students)
students.pop(3)
print("Remove student at index 3 'pop()':", students)
print("Total Student:", len(students))
print("Total students from  1 to 4 :", students[1:4])
students.reverse()
print("Reverse the List:", students)
print("Final List:", students)

# Q3 — Mobile Prices Analysis
print("======================================================")
print("            Q3 — Mobile Prices Analysis")
print("======================================================")
prices = [45000, 120000, 30000, 85000, 60000]
prices.sort()
print("Higest Price After Sorting:", prices[-1])
print("Lowest Price:", prices[0])
print("Sort prices in Ascending order:", prices)
prices.sort(reverse=True)
print("Sort prices in Descending order:", prices)
prices.append(100000)
print("Add new mobile price:", prices)
prices.remove(30000)
print("Remove one price using remove()", prices)
prices.pop()
print("Remove last price using pop():", prices)
print("Print first 3 prices:", prices[0:4])
print("Print last 2 prices:", prices[-2:] )
print("Print Total number of prices:", len(prices))

# Q4 — Cricket Team Management
print("======================================================")
print("            Q4 — Cricket Team Management")
print("======================================================")
players = ["Babar", "Rizwan", "Shaheen", "Naseem", "Shadab"]
print("Captain name using indexing:", players[2])
print("Last player using negative indexing:", players[-1])
players[-1] = "Imad"
print("Replace 'Shadab' with 'Imad':", players)
players.append("Salman")
print("Add one new player:", players)
players.insert(2, "Iftikhar")
print("Insert one player at index 2:", players)
players.remove("Naseem")
print('Remove "Naseem":', players)
print("Print first 4 players:", players[0:5])
print("Print last 3 players:",players[-3:])
players.reverse()
print("Reverse the team list:", players)
print("Final Squad:", players)

# Q5 — Shopping Cart System
print("======================================================")
print("           Q5 — Shopping Cart System")
print("======================================================")
cart = ["Shoes", "Watch", "Bag", "Laptop", "Bottle"]
print("First cart item:", cart[0])
print("last item:", cart[-1])
cart[-1] = "Headphones"
print('Replace "Bottle" with "Headphones":', cart)
cart.append("Keyboard")
print('Add "Keyboard":', cart)
cart.insert(1, "Mouse")
print('Insert "Mouse" at index 1:', cart)
cart.remove("Bag")
print('Remove "Bag":', cart)
cart.pop(-1)
print("Remove last item using pop():", cart)
print("Total cart items:", len(cart))
print("Middle 3 items:", cart[1:4])
cart.reverse()
print("Reverse the list:", cart)
print("Updated Cart:", cart)

# Q6 — Employee Salary Records
print("======================================================")
print("          Q6 — Employee Salary Records")
print("======================================================")
salaries = [25000, 40000, 70000, 55000, 90000]
print("Highest salary:", salaries[-1])
print("Lowest salary:", salaries[0])
salaries.sort()
print("Sort salaries in ascending order:", salaries)
salaries.sort(reverse=True)
print("Sort salaries in descending order:", salaries)
salaries.append("60000")
print("Add one more salary:", salaries)
salaries.remove("60000")
print("Remove one salary:", salaries)
print("Second highest salary:", salaries[1])
print("First 3 salaries:", salaries[0:4])
print("Total salaries count:", len(salaries))
print("Final List:", salaries)

# Q7 — Movie Collection System
print("======================================================")
print("          Q7 — Movie Collection System")
print("======================================================")
movies = ["Avatar", "Inception", "Joker", "Titanic", "Interstellar"]
print("Firt Movie:", movies[0])
print("Last movie (using negative indexing):", movies[-1])
movies[2] = "Batman"
print('Replace "Joker" with "Batman":', movies)
movies.append("Obsesion")
print("Add one new movie:", movies)
movies.insert(3, "Strange-Things")
print("Insert one movie at index 3:", movies)
movies.remove("Titanic")
print('Remove "Titanic"', movies)
movies.pop()
print("Remove last movie using pop()", movies)
print("First 4 movies:", movies[0:5])
movies.reverse()
print("Reverse movie list:", movies)
print("Final updated movie collection:", movies)

# Q8 — Exam Marks Analysis
print("======================================================")
print("          Q8 — Exam Marks Analysis")
print("======================================================")
marks = [78, 45, 90, 66, 82]
print("Highest marks", marks[2])
print("Lowest marks:", movies[1])
marks.sort()
print("Sort marks:", marks)
marks.sort(reverse=True)
print("Sort marks in descending order:", marks)
marks.append(80)
print("Add new marks:", marks)
marks.remove(45)
print("Remove failed marks using remove():", marks)
print("Top 3 marks:", marks[0:3])
print("Last 2 marks:", marks[-2:])
print("Total subjects using len():", len(marks))
print("Final marks list:", marks)

# Q9 — Website Visitors Record
print("======================================================")
print("          Q9 — Website Visitors Record")
print("======================================================")
visitors = ["Ali", "Sara", "Ahmed", "Zoha Khan", "Hira"]
print("First visitor:", visitors[0])
print("Last visitor:", visitors[-1])
visitors.append("Adil")
print("Add one new visitor:", visitors)
visitors.insert(2, "Alice")
print("Insert one visitor at index 2:", visitors)
visitors.remove("Ahmed")
print('Remove "Ahmed":', visitors)
visitors.pop()
print("Remove last visitor using pop():", visitors)
print("First 3 visitors:", visitors[0:3])
print("Last 3 visitors:", visitors[-3:])
visitors.reverse()
print("Reverse visitors list:", visitors)
print("Total visitors:", visitors)

# Q10 — Programming Languages System
print("======================================================")
print("          Q10 — Programming Languages System")
print("======================================================")
languages = ["Python", "JavaScript", "Java", "C++", "PHP"]
print("First language:", languages[0])
print("Last language using negative indexing:", languages[-1])
languages[-1] = "TypeScript"
print('Replace "PHP" with "TypeScript":', languages)
languages.append("Go")
print('Add "Go":', languages)
languages.insert(2, "Rust")
print('Insert "Rust" at index 2:', languages)
languages.remove("Java")
print('Remove "Java":', languages)
print("First 4 languages:", languages[0:4])
print("Last 2 languages:", languages[0:2])
languages.sort()
print("Sort languages alphabetically:", languages)
languages.reverse()
print("Reverse the list:", languages)
print("Final Updated Languages List:", languages) 
